# Numpy Exercise Solution  <img src = "numpy1.png">
###### Authored by 

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [2]:
import numpy as np
x = np.random.randint(10,32,28)

array([20, 13, 18, 18, 11, 21, 19, 27, 28, 25, 23, 17, 16, 11, 15, 18, 23,
       26, 20, 22, 23, 28, 23, 12, 26, 27, 14, 23])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [11]:
y = np.arange(1,50,2)
len(y)

25

#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [12]:
np.linspace(4,7,27)

array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [13]:
np.random.rand(5,4)
#how to specify decimal points

array([[0.5172729 , 0.23090478, 0.81439646, 0.74677946],
       [0.25966492, 0.21320519, 0.56154274, 0.32126813],
       [0.9512773 , 0.95862848, 0.46312607, 0.52132791],
       [0.21491147, 0.40961918, 0.55421941, 0.91000798],
       [0.62788269, 0.95351652, 0.24194204, 0.53893188]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [14]:
np.random.randint(5,15,size = (5,5))

array([[ 5,  6,  9, 12,  9],
       [ 5, 11,  7, 11, 10],
       [10,  7,  9,  7, 12],
       [ 7, 10, 13,  6, 12],
       [10, 11,  8, 10,  8]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [23]:
np.zeros(np.random.randint(1,20,dtype='int32'))

array([0.])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [41]:
from numpy import random
np.ones((random.randint(1,10),random.randint(1,10)),dtype='float32')

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [43]:
s = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
s

array([[ 9, 25, 50, 34, 45],
       [ 3, 34, 34, 65,  2],
       [ 5,  7,  3, 76,  3],
       [ 7,  8,  6, 54,  6],
       [23, 12,  8,  5,  8]])

#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [44]:
# Solution
s[2][2]

3

#### 10. Print the all the elements of 3rd row of the matrix

In [59]:
# Solution
s[2]

array([ 5,  7,  3, 76,  3])

#### 11. Print the all the elements of 4th columns of the matrix

In [60]:
# Solution
s[:,3]

array([34, 65, 76, 54,  5])

#### 12. Print the 4 corner pixels of the matrix

In [68]:
# Solution
s[[0,4,4,0],[0,4,0,4]]


array([ 9,  8, 23, 45])

#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [119]:
# Solution 
m1 = s[:2,2:4]
m2 = s[3:,0:2]
m3 = s[2:,2:]

print(m1,'\n')
print(m2,'\n')
print(m3,'\n')

[[50 34]
 [34 65]] 

[[ 7  8]
 [23 12]] 

[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]] 



#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [112]:
m1 = m1.reshape(1,4)
m2 = m2.reshape(1,4)
m3 = m3.reshape(1,9)

print(m1,'\n')
print(m2,'\n')
print(m3,'\n')

[[50 34 34 65]] 

[[ 7  8 23 12]] 

[[ 3 76  3  6 54  6  8  5  8]] 



#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [118]:
# Solution
r = np.concatenate([m1,m2])
t = np.hstack([m1,m2])
print(r)
print(t)

[[50 34 34 65]
 [ 7  8 23 12]]
[[50 34 34 65  7  8 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [122]:
# Solution
print(m1+m2,'\n')

print(m1-m2,'\n')

print(m1*m2,'\n')

print(m1/m2,'\n')

print()

[[57 42]
 [57 77]] 

[[43 26]
 [11 53]] 

[[350 272]
 [782 780]] 

[[7.14285714 4.25      ]
 [1.47826087 5.41666667]] 




#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [135]:
# Solution
m1+m3[1:,:2]

array([[56, 88],
       [42, 70]])

#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [143]:
# Solution
me1 = np.mean(m1)
me2 = np.mean(m2)
m4 = np.vstack([m1,np.array([me1,me2])])
m4

array([[50.  , 34.  ],
       [34.  , 65.  ],
       [45.75, 12.5 ]])

#### 19. Perform the matrix multiplication between m3 and m4

In [146]:
# Solution
m3@m4

array([[2871.25, 5079.5 ],
       [2410.5 , 3789.  ],
       [ 936.  ,  697.  ]])

#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [180]:
# Solution
means = []
variances =  []
stand_dev = []
for i in range(s.shape[0]):
    means.append(s[i].mean())
    variances.append(s[i].var())
    stand_dev.append(s[i].std())

means = np.array(means)
variances = np.array(variances)
stand_dev = np.array(stand_dev)  

In [181]:
print('Mean; Max ',max(means),' Min ',min(means))
print('Variance; Max ',max(variances),' Min ',min(variances))
print('Stand Dev; Max ',max(stand_dev),' Min ',min(stand_dev))

Mean; Max  32.6  Min  11.2
Variance; Max  820.1600000000001  Min  39.760000000000005
Stand Dev; Max  28.63843571147  Min  6.305553108173779


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [3]:
import numpy as np

In [47]:
runs = np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
balls = np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])

avg = np.array([np.mean(i) for i in runs])
stkrate = np.array([np.sum(i) for i in runs])/np.array([np.sum(i) for i in balls])
print("\t\tMSD\tKholi\tRohit\tRahul\tDhawan")
print("\t".join(["AVERAGE\t"]+[str(nums) for nums in avg.round(2)]))
print("\t".join(["STRIKE RATE"]+[str(nums) for nums in stkrate.round(4)]))

		MSD	Kholi	Rohit	Rahul	Dhawan
AVERAGE		47.25	53.5	51.5	29.0	13.25
STRIKE RATE	0.9844	1.0142	0.9493	1.6111	0.4953


In [37]:
print("\t".join([str(nums) for nums in avg.round(2)]))


47.25	53.5	51.5	29.0	13.25


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [72]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
passed = np.count_nonzero(marks >= 50)
failed = np.count_nonzero(marks < 50)

print(passed, 'students Passed and',failed,'Failed the exam')


7 students Passed and 3 Failed the exam


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [81]:
adj_marks = np.array([i+5 if (i>=45 and i<=49) or (i>=80 and i<=100) else i for i in marks ])
adj_marks = np.array([100 if i>100 else i for i in adj_marks ])
print("MERCY MARKS:\t",''.join(str(adj_marks).replace('[','').replace(']','')))
print("ORIGINAL MARKS:\t",''.join(str(marks)).replace('[','').replace(']',''))


MERCY MARKS:	  65  89  52  56  94 100  53  77  85  39
ORIGINAL MARKS:	 65 84 47 56 89 98 48 77 80 39


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [95]:
import time
tic = time.time()
x = np.array(range(1,60001))
y = np.array(range(1,60001))

(x**2+8)/y
toc = time.time()

print('Time Elapsed: ',round(toc-tic,5),'s')


Time Elapsed:  0.01985 s


#### 25. Create a Github account and upload your solution with the short write-up on Numpy